baseURL = "https://ravibuddi.com"
languageCode = "en-us"
title = "r3motecontrol"

theme = "hugo-coder"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true






[params]
	author = "Ravi Buddi"
	description = "Personal website"
	
	hideCredits = false
	hideCopyright = false


	#Custom CSS
        custom_css = []


[[params.social]]
	name = "Github"
	weight = 1
	url = "https://github.com/r3motecontrol"

[[params.social]]
	name = "LinkedIn"
	weight = 2
	url = "https://www.linkedin.com/in/ravi-buddi"



[[menu.main]]
	name = "Blog"
	weight = 1
	url = "/posts/"
	
[[menu.main]]
	name = "Resume"
	weight = 2
	url = "/resume.pdf"


